[package]
name = "svg2librepcb"
version = "0.1.0"
authors = ["Danilo Bargen <mail@dbrgn.ch>"]
edition = "2018"

[dependencies]
chrono = "0.4"
clap = "2"
quick-error = "1.2.2"
svg2polylines = "0.5.1"
uuid = { version = "0.7", features = ["v4"] }
